version: '3'

services:
  app:
    build: './app'
    ports:
      - '8000:8000'
    environment:
      HOST: '0.0.0.0'
      PORT: '8000'
  frontend:
    build: './frontend'
    ports:
      - '3000:3000'
    environment:
      REACT_PORT: 3000
      REACT_APP_API_URL: 'http://localhost:8000'
    depends_on:
      - app

